//! @file
//!
//! This source file was generated from CellML by chaste_codegen version 0.9.11
//!
//! Model: ICC
//!
//! Processed by chaste_codegen: https://github.com/ModellingWebLab/chaste-codegen
//!     (translator: chaste_codegen, model type: Normal)
//! on 2023-04-09 22:46:46
//!
//! <autogenerated>

#include "ICC_SMC_BP.hpp"
#include <cmath>
#include <cassert>
#include <memory>
#include "Exception.hpp"
#include "OdeSystemInformation.hpp"
#include "RegularStimulus.hpp"
#include "HeartConfig.hpp"
#include "IsNan.hpp"
#include "MathsCustomFunctions.hpp"





    double CellICC_SMC_BPFromCellML::GetIntracellularCalciumConcentration()
    {
        return mStateVariables[1];
    }
    CellICC_SMC_BPFromCellML::CellICC_SMC_BPFromCellML(boost::shared_ptr<AbstractIvpOdeSolver> pSolver, boost::shared_ptr<AbstractStimulusFunction> pIntracellularStimulus)
        : AbstractCardiacCell(
                pSolver,
                31,
                0,
                pIntracellularStimulus)
    {
        // Time units: millisecond
        //
        this->mpSystemInfo = OdeSystemInformation<CellICC_SMC_BPFromCellML>::Instance();
        Init();
        
        this->mParameters[0] = 0.025000000000000001; // (var_ICC_Membrane__Cm) [capacitance_units_ICC]
        this->mParameters[1] = 5000; // (var_Parameters__K_o) [micromolar]
        this->mParameters[2] = 0; // (var_neural_input__x_e) [Hertz]
        this->mParameters[3] = 0; // (var_neural_input__x_i) [Hertz]
    }

    CellICC_SMC_BPFromCellML::~CellICC_SMC_BPFromCellML()
    {
    }

    
    double CellICC_SMC_BPFromCellML::GetIIonic(const std::vector<double>* pStateVariables)
    {
        // For state variable interpolation (SVI) we read in interpolated state variables,
        // otherwise for ionic current interpolation (ICI) we use the state variables of this model (node).
        if (!pStateVariables) pStateVariables = &rGetStateVariables();
        const std::vector<double>& rY = *pStateVariables;
        double var_chaste_interface__ICC_Membrane__Vm = (mSetVoltageDerivativeToZero ? this->mFixedVoltage : rY[0]);
        // Units: voltage_units; Initial value: -66.0
        double var_chaste_interface__d_CaT__d_CaT = rY[16];
        // Units: dimensionless; Initial value: 0.001271016263081
        double var_chaste_interface__f_CaT__f_CaT = rY[17];
        // Units: dimensionless; Initial value: 0.5
        double var_chaste_interface__d_CaV__d_CaV = rY[18];
        // Units: dimensionless; Initial value: 0.001271016263081
        double var_chaste_interface__d_NaV__d_NaV = rY[19];
        // Units: dimensionless; Initial value: 0.0006607800216060858
        double var_chaste_interface__f_NaV__f_NaV = rY[20];
        // Units: dimensionless; Initial value: 1.0
        double var_chaste_interface__d_KV__d_KV = rY[21];
        // Units: dimensionless; Initial value: 0.01
        double var_chaste_interface__f_KV__f_KV = rY[22];
        // Units: dimensionless; Initial value: 0.583726132461315
        double var_chaste_interface__d_NSV__d_NSV = rY[23];
        // Units: dimensionless; Initial value: 0.001271016263081
        double var_chaste_interface__f_NSV__f_NSV = rY[24];
        // Units: dimensionless; Initial value: 0.5
        double var_chaste_interface__d_KERG__d_KERG = rY[25];
        // Units: dimensionless; Initial value: 0.001
        double var_chaste_interface__f_KERG__f_KERG = rY[26];
        // Units: dimensionless; Initial value: 0.001
        double var_chaste_interface__d_Ano1__d_Ano1 = rY[27];
        // Units: dimensionless; Initial value: 0.01
        double var_chaste_interface__Ca_er__Ca_er = rY[28];
        // Units: micromolar; Initial value: 290.0
        double var_chaste_interface__ICC_Membrane__Ca_i = rY[30];
        // Units: micromolar; Initial value: 0.14
        
        const double var_ICC_Membrane__Cm_converted = 0.001 * mParameters[0]; // uF
        const double var_I_Ano1__g_Ano1 = 20; // conductance_units
        const double var_I_BK__g_BK = 9; // conductance_units
        const double var_I_BNa__g_BNa = 2; // conductance_units
        const double var_I_CaT__g_CaT = 4; // conductance_units
        const double var_I_CaV__g_CaV = 0; // conductance_units
        const double var_I_KERG__g_KERG = 0; // conductance_units
        const double var_I_KV__g_KV = 0; // conductance_units
        const double var_I_NCX__switch_NCX = 0; // dimensionless
        const double var_I_NCX__v_NCX = 225; // micromolar_per_second
        const double var_I_NCX__J_NCX = var_chaste_interface__ICC_Membrane__Ca_i * var_I_NCX__switch_NCX * var_I_NCX__v_NCX / (3.6000000000000001 + var_chaste_interface__ICC_Membrane__Ca_i); // micromolar_per_second
        const double var_I_NSCC__g_NSCC = 30; // rate_constants_units_second
        const double var_I_NSV__g_NSV = 0; // conductance_units
        const double var_I_NaV__a_HCl_NaV = 1; // dimensionless
        const double var_I_NaV__a_LCl_NaV = 0; // dimensionless
        const double var_I_NaV__g_NaV = 0; // conductance_units
        const double var_I_SOC__SOCPropCa = 1; // dimensionless
        const double var_I_SOC__g_SOC = 0.10000000000000001; // conductance_units
        const double var_Nernst__E_NSCC = 0; // voltage_units
        const double var_Nernst__E_NSV = 0; // voltage_units
        const double var_P_NSCC__Ca_NSCC = 1.8; // micromolar
        const double var_P_NSCC__n_NSCC = 4; // dimensionless
        const double var_P_NSCC__P_NSCC = pow(var_chaste_interface__ICC_Membrane__Ca_i, var_P_NSCC__n_NSCC) / (pow(var_chaste_interface__ICC_Membrane__Ca_i, var_P_NSCC__n_NSCC) + pow(var_P_NSCC__Ca_NSCC, var_P_NSCC__n_NSCC)); // dimensionless
        const double var_P_SOC__SOC_h = 200; // micromolar
        const double var_P_SOC__SOC_n = 8; // dimensionless
        const double var_P_SOC__P_SOC = 1 / (1 + pow((var_chaste_interface__Ca_er__Ca_er / var_P_SOC__SOC_h), var_P_SOC__SOC_n)); // dimensionless
        const double var_Parameters__Ca_o = 2000; // micromolar
        const double var_Parameters__Cl_i = 78000; // micromolar
        const double var_Parameters__Cl_o = 166000; // micromolar
        const double var_Parameters__F = 96.4846; // F_units_ICC
        const double var_Parameters__K_i = 140000; // micromolar
        const double var_Parameters__Na_i = 30000; // micromolar
        const double var_Parameters__Na_o = 140000; // micromolar
        const double var_Parameters__R = 8.3143999999999991; // R_units_ICC
        const double var_Parameters__T = 310; // Temperature_units
        const double var_Parameters__p2m = 1.0000000000000001e-9; // dimensionless
        const double var_Parameters__z_ca = 2; // dimensionless
        const double var_Nernst__E_Ca = var_Parameters__R * var_Parameters__T * log(var_Parameters__Ca_o / var_chaste_interface__ICC_Membrane__Ca_i) / (var_Parameters__F * var_Parameters__z_ca); // voltage_units
        const double var_I_SOC__I_SOC = (-var_Nernst__E_Ca + var_chaste_interface__ICC_Membrane__Vm) * var_I_SOC__g_SOC * var_P_SOC__P_SOC; // current_units
        const double var_Parameters__z_cl = -1; // dimensionless
        const double var_Nernst__E_Cl = var_Parameters__R * var_Parameters__T * log(var_Parameters__Cl_o / var_Parameters__Cl_i) / (var_Parameters__F * var_Parameters__z_cl); // voltage_units
        const double var_Parameters__z_k = 1; // dimensionless
        const double var_Nernst__E_K = var_Parameters__R * var_Parameters__T * log(mParameters[1] / var_Parameters__K_i) / (var_Parameters__F * var_Parameters__z_k); // voltage_units
        const double var_I_BK__I_BK = (-var_Nernst__E_K + var_chaste_interface__ICC_Membrane__Vm) * var_I_BK__g_BK; // current_units
        const double var_Parameters__z_na = 1; // dimensionless
        const double var_Nernst__E_Na = var_Parameters__R * var_Parameters__T * log(var_Parameters__Na_o / var_Parameters__Na_i) / (var_Parameters__F * var_Parameters__z_na); // voltage_units
        const double var_I_BNa__I_BNa = (-var_Nernst__E_Na + var_chaste_interface__ICC_Membrane__Vm) * var_I_BNa__g_BNa; // current_units
        const double var_ICC_Membrane__I_dummy = 0; // current_units
        const double var_Volume__cellPropCyto = 0.69999999999999996; // dimensionless
        const double var_Volume__cellVol = 9.9999999999999998e-13; // liter
        const double var_Volume__volCyto = var_Volume__cellPropCyto * var_Volume__cellVol; // liter
        const double var_I_NCX__I_NCX = -var_I_NCX__J_NCX * var_I_NCX__switch_NCX * var_I_SOC__SOCPropCa * var_Parameters__F * var_Parameters__z_ca * var_Volume__volCyto / var_Parameters__p2m; // current_units
        const double var_I_SOC__J_SOC = -var_I_SOC__I_SOC * var_I_SOC__SOCPropCa * var_Parameters__p2m / (var_Parameters__F * var_Parameters__z_ca * var_Volume__volCyto); // micromolar_per_second
        const double var_d_Ano1__Ano1_Vh = -100; // voltage_units
        const double var_d_Ano1__Ano1_n = 2; // dimensionless
        const double var_d_Ano1__Ano1_s = 0.015599999999999999; // voltage_units
        const double var_d_Ano1__Bm = 50; // micromolar
        const double var_d_Ano1__Dc = 250; // micrometer2_per_time
        const double var_d_Ano1__Dm = 75; // micrometer2_per_time
        const double var_d_Ano1__Km = 1; // micromolar
        const double var_d_Ano1__colocalRadius = 0.050000000000000003; // micrometer
        const double var_d_Ano1__d_Ano1_tscale = 1; // dimensionless
        const double var_d_Ano1__kc = 0.01248; // Inverse_Voltage_ICC
        const double var_d_Ano1__nSOC = 50; // dimensionless
        const double var_d_Ano1__mouthCa = 1000000000000000.0 * var_I_SOC__J_SOC * var_Volume__volCyto / var_d_Ano1__nSOC; // micromolar_per_second
        const double var_d_Ano1__rad = var_d_Ano1__colocalRadius; // micrometer
        const double var_d_Ano1__localCa = 0.5 * (2 * sqrt(0.25 * pow((var_chaste_interface__ICC_Membrane__Ca_i * var_d_Ano1__Dc + var_d_Ano1__Dc * var_d_Ano1__Km + 0.5 * var_d_Ano1__mouthCa / (M_PI * var_d_Ano1__rad) - var_d_Ano1__Bm * var_d_Ano1__Dm * var_d_Ano1__Km / (var_chaste_interface__ICC_Membrane__Ca_i + var_d_Ano1__Km)), 2) + var_d_Ano1__Bm * var_d_Ano1__Dc * var_d_Ano1__Dm * var_d_Ano1__Km) + var_chaste_interface__ICC_Membrane__Ca_i * var_d_Ano1__Dc - var_d_Ano1__Dc * var_d_Ano1__Km + 0.5 * var_d_Ano1__mouthCa / (M_PI * var_d_Ano1__rad) - var_d_Ano1__Bm * var_d_Ano1__Dm * var_d_Ano1__Km / (var_chaste_interface__ICC_Membrane__Ca_i + var_d_Ano1__Km)) / var_d_Ano1__Dc; // micromolar
        const double var_d_Ano1__d_Ano1_inf = 1 / ((1 + pow((0.71942446043165476 * var_d_Ano1__localCa / exp(-var_chaste_interface__ICC_Membrane__Vm * var_d_Ano1__kc)), (-var_d_Ano1__Ano1_n))) * (1 + exp((-var_chaste_interface__ICC_Membrane__Vm + var_d_Ano1__Ano1_Vh) * var_d_Ano1__Ano1_s))); // dimensionless
        const double var_d_Ano1__d_Ano1_tau = 0.001 * (81.629999999999995 * exp(-0.56999999999999995 * var_d_Ano1__localCa) + 76.170000000000002 * exp(-0.053740000000000003 * var_d_Ano1__localCa) * exp(0.01422475106685633 * var_chaste_interface__ICC_Membrane__Vm / exp(0.153 * var_d_Ano1__localCa))) * var_d_Ano1__d_Ano1_tscale; // time_units_ICC
        const double var_I_CaV__I_CaV = (-var_Nernst__E_Ca + var_chaste_interface__ICC_Membrane__Vm) * var_I_CaV__g_CaV * var_chaste_interface__d_CaV__d_CaV; // current_units
        const double var_I_CaT__I_CaT = (-var_Nernst__E_Ca + var_chaste_interface__ICC_Membrane__Vm) * var_I_CaT__g_CaT * var_chaste_interface__d_CaT__d_CaT * var_chaste_interface__f_CaT__f_CaT; // current_units
        const double var_I_KERG__I_KERG = (-var_Nernst__E_K + var_chaste_interface__ICC_Membrane__Vm) * var_I_KERG__g_KERG * var_chaste_interface__d_KERG__d_KERG * var_chaste_interface__f_KERG__f_KERG; // current_units
        const double var_I_KV__I_KV = (-var_Nernst__E_K + var_chaste_interface__ICC_Membrane__Vm) * var_I_KV__g_KV * var_chaste_interface__d_KV__d_KV * var_chaste_interface__f_KV__f_KV; // current_units
        const double var_I_NSV__I_NSV = (-var_Nernst__E_NSV + var_chaste_interface__ICC_Membrane__Vm) * var_I_NSV__g_NSV * var_chaste_interface__d_NSV__d_NSV * var_chaste_interface__f_NSV__f_NSV; // current_units
        const double var_I_NaV__f_NaV_new = var_I_NaV__a_LCl_NaV * var_chaste_interface__f_NaV__f_NaV + var_I_NaV__a_HCl_NaV; // dimensionless
        const double var_I_NaV__I_NaV = (-var_Nernst__E_Na + var_chaste_interface__ICC_Membrane__Vm) * var_I_NaV__f_NaV_new * var_I_NaV__g_NaV * var_chaste_interface__d_NaV__d_NaV; // current_units
        const double var_neural_input__Ano1_effect = 0.5; // dimensionless
        const double var_neural_input__NSCC_effect = 0.5; // dimensionless
        const double var_neural_input__S_i = mParameters[3]; // dimensionless
        const double var_neural_input__S_i_Ano1 = var_neural_input__Ano1_effect * var_neural_input__S_i; // dimensionless
        const double var_d_Ano1__inh_Ano1 = var_chaste_interface__d_Ano1__d_Ano1 * var_neural_input__S_i_Ano1 / (1 + pow((-var_chaste_interface__d_Ano1__d_Ano1 + var_d_Ano1__d_Ano1_inf), 2) / pow(var_d_Ano1__d_Ano1_tau, 2)); // dimensionless
        const double var_I_Ano1__I_Ano1 = (-var_Nernst__E_Cl + var_chaste_interface__ICC_Membrane__Vm) * (-var_d_Ano1__inh_Ano1 + var_chaste_interface__d_Ano1__d_Ano1) * var_I_Ano1__g_Ano1; // current_units
        const double var_neural_input__S_i_NSCC = var_neural_input__NSCC_effect * var_neural_input__S_i; // dimensionless
        const double var_I_NSCC__inh_scale_NSCC = 1 - var_neural_input__S_i_NSCC; // dimensionless
        const double var_I_NSCC__I_NSCC = (-var_Nernst__E_NSCC + var_chaste_interface__ICC_Membrane__Vm) * var_I_NSCC__g_NSCC * var_I_NSCC__inh_scale_NSCC * var_P_NSCC__P_NSCC; // current_units
        const double var_ICC_Membrane__Iion = var_ICC_Membrane__I_dummy + var_I_Ano1__I_Ano1 + var_I_BK__I_BK + var_I_BNa__I_BNa + var_I_CaT__I_CaT + var_I_CaV__I_CaV + var_I_KERG__I_KERG + var_I_KV__I_KV + var_I_NCX__I_NCX + var_I_NSCC__I_NSCC + var_I_NSV__I_NSV + var_I_NaV__I_NaV + var_I_SOC__I_SOC; // current_units
        const double var_chaste_interface__i_ionic = 1.0000000000000002e-6 * HeartConfig::Instance()->GetCapacitance() * var_ICC_Membrane__Iion / var_ICC_Membrane__Cm_converted; // uA_per_cm2

        const double i_ionic = var_chaste_interface__i_ionic;
        EXCEPT_IF_NOT(!std::isnan(i_ionic));
        return i_ionic;
    }

    void CellICC_SMC_BPFromCellML::EvaluateYDerivatives(double var_chaste_interface__Time__time, const std::vector<double>& rY, std::vector<double>& rDY)
    {
        // Inputs:
        // Time units: millisecond
        double var_chaste_interface__ICC_Membrane__Vm = (mSetVoltageDerivativeToZero ? this->mFixedVoltage : rY[0]);
        // Units: voltage_units; Initial value: -66.0
        double var_chaste_interface__SM_Membrane__Ca_i = rY[1];
        // Units: millimolar; Initial value: 8e-05
        double var_chaste_interface__SM_Membrane__Vm_SM = rY[2];
        // Units: voltage_units; Initial value: -69.75
        double var_chaste_interface__d_Ltype_SM__d_Ltype_SM = rY[3];
        // Units: dimensionless; Initial value: 0.0
        double var_chaste_interface__f_Ltype_SM__f_Ltype_SM = rY[4];
        // Units: dimensionless; Initial value: 0.95
        double var_chaste_interface__f_ca_Ltype_SM__f_ca_Ltype_SM = rY[5];
        // Units: dimensionless; Initial value: 1.0
        double var_chaste_interface__d_LVA_SM__d_LVA_SM = rY[6];
        // Units: dimensionless; Initial value: 0.02
        double var_chaste_interface__f_LVA_SM__f_LVA_SM = rY[7];
        // Units: dimensionless; Initial value: 0.99
        double var_chaste_interface__x_SK_SM__x_SK_SM = rY[8];
        // Units: dimensionless; Initial value: 0.0
        double var_chaste_interface__xr1_SM__xr1_SM = rY[9];
        // Units: dimensionless; Initial value: 0.0
        double var_chaste_interface__xr2_SM__xr2_SM = rY[10];
        // Units: dimensionless; Initial value: 0.82
        double var_chaste_interface__m_Na_SM__m_Na_SM = rY[11];
        // Units: dimensionless; Initial value: 0.005
        double var_chaste_interface__h_Na_SM__h_Na_SM = rY[12];
        // Units: dimensionless; Initial value: 0.05787
        double var_chaste_interface__xa1_SM__xa1_SM = rY[13];
        // Units: dimensionless; Initial value: 0.00414
        double var_chaste_interface__xa2_SM__xa2_SM = rY[14];
        // Units: dimensionless; Initial value: 0.72
        double var_chaste_interface__m_NSCC_SM__m_NSCC_SM = rY[15];
        // Units: dimensionless; Initial value: 0.0
        double var_chaste_interface__d_CaT__d_CaT = rY[16];
        // Units: dimensionless; Initial value: 0.001271016263081
        double var_chaste_interface__f_CaT__f_CaT = rY[17];
        // Units: dimensionless; Initial value: 0.5
        double var_chaste_interface__d_CaV__d_CaV = rY[18];
        // Units: dimensionless; Initial value: 0.001271016263081
        double var_chaste_interface__d_NaV__d_NaV = rY[19];
        // Units: dimensionless; Initial value: 0.0006607800216060858
        double var_chaste_interface__f_NaV__f_NaV = rY[20];
        // Units: dimensionless; Initial value: 1.0
        double var_chaste_interface__d_KV__d_KV = rY[21];
        // Units: dimensionless; Initial value: 0.01
        double var_chaste_interface__f_KV__f_KV = rY[22];
        // Units: dimensionless; Initial value: 0.583726132461315
        double var_chaste_interface__d_NSV__d_NSV = rY[23];
        // Units: dimensionless; Initial value: 0.001271016263081
        double var_chaste_interface__f_NSV__f_NSV = rY[24];
        // Units: dimensionless; Initial value: 0.5
        double var_chaste_interface__d_KERG__d_KERG = rY[25];
        // Units: dimensionless; Initial value: 0.001
        double var_chaste_interface__f_KERG__f_KERG = rY[26];
        // Units: dimensionless; Initial value: 0.001
        double var_chaste_interface__d_Ano1__d_Ano1 = rY[27];
        // Units: dimensionless; Initial value: 0.01
        double var_chaste_interface__Ca_er__Ca_er = rY[28];
        // Units: micromolar; Initial value: 290.0
        double var_chaste_interface__y_bind__y = rY[29];
        // Units: dimensionless; Initial value: 0.4
        double var_chaste_interface__ICC_Membrane__Ca_i = rY[30];
        // Units: micromolar; Initial value: 0.14

        // Mathematics
        double d_dt_chaste_interface_var_ICC_Membrane__Vm;
        const double var_Environment__Ca_o = 2.5; // millimolar
        const double var_Environment__F = 96486; // F_units
        const double var_Environment__K_o = 5.9000000000000004; // millimolar
        const double var_Environment__Na_o = 137; // millimolar
        const double var_Environment__Q10Ca = 2.1000000000000001; // dimensionless
        const double var_Environment__Q10K = 1.365; // dimensionless
        const double var_Environment__Q10Na = 2.4500000000000002; // dimensionless
        const double var_Environment__R = 8314.3999999999996; // R_units
        const double var_Environment__T = 310; // Temperature_units
        const double var_Environment__RToF = var_Environment__R * var_Environment__T / var_Environment__F; // voltage_units
        const double var_Environment__T_exp = 297; // Temperature_units
        const double var_Environment__T_correction_BK = 1.1000000000000001 * var_Environment__T - 1.1000000000000001 * var_Environment__T_exp; // conductance_units
        const double var_Environment__T_correction_Ca = pow(var_Environment__Q10Ca, (0.10000000000000001 * var_Environment__T - 0.10000000000000001 * var_Environment__T_exp)); // dimensionless
        const double var_Environment__T_correction_K = pow(var_Environment__Q10K, (0.10000000000000001 * var_Environment__T - 0.10000000000000001 * var_Environment__T_exp)); // dimensionless
        const double var_Environment__T_correction_Na = pow(var_Environment__Q10Na, (0.10000000000000001 * var_Environment__T - 0.10000000000000001 * var_Environment__T_exp)); // dimensionless
        const double var_I_BK_SM__G_max_BK = 45.700000000000003; // conductance_units
        const double var_I_CaT__g_CaT = 4; // conductance_units
        const double var_I_CaV__g_CaV = 0; // conductance_units
        const double var_I_LVA_SM__G_max_LVA = 0.17999999999999999; // conductance_units
        const double var_I_Ltype_SM__G_max_Ltype = 65; // conductance_units
        const double var_I_NCX__switch_NCX = 0; // dimensionless
        const double var_I_NCX__v_NCX = 225; // micromolar_per_second
        const double var_I_NCX__J_NCX = var_chaste_interface__ICC_Membrane__Ca_i * var_I_NCX__switch_NCX * var_I_NCX__v_NCX / (3.6000000000000001 + var_chaste_interface__ICC_Membrane__Ca_i); // micromolar_per_second
        const double var_I_NSCC_SM__Ach = 1.0000000000000001e-5; // millimolar
        const double var_I_NSCC_SM__E_NSCC = -28; // voltage_units
        const double var_I_NSCC_SM__G_max_NSCC_SM = 50; // conductance_units
        const double var_I_NSCC_SM__rach_NSCC_SM = 1 / (1 + 0.01 / var_I_NSCC_SM__Ach); // dimensionless
        const double var_I_Na_SM__G_max_Na_SM = 3; // conductance_units
        const double var_I_SK_SM__G_max_SK = 3.5; // conductance_units
        const double var_I_SOC__SOCPropCa = 1; // dimensionless
        const double var_I_SOC__g_SOC = 0.10000000000000001; // conductance_units
        const double var_I_bk_SM__G_max_bk = 0.0144; // conductance_units
        const double var_I_couple__g_couple = 1.3; // conductance_units
        const double var_I_ka_SM__G_max_ka_SM = 9; // conductance_units
        const double var_I_kr_SM__G_max_kr_SM = 35; // conductance_units
        const double var_J_CaSR_SM__J_max_CaSR = 0.31705; // millimolar_per_millisecond
        const double var_J_IPR__IP3_base = 0.5; // micromolar
        const double var_J_IPR__Jer = 0.01; // rate_constants_units_second
        const double var_J_IPR__kipr = 7; // rate_constants_units_second
        const double var_J_PMCA__J_PMCA_max = 100; // micromolar_per_second
        const double var_J_PMCA__K_PMCA = 0.10000000000000001; // micromolar
        const double var_J_PMCA__g_PMCA = 1; // dimensionless
        const double var_J_PMCA__n_PMCA = 2; // dimensionless
        const double var_J_PMCA__J_PMCA = var_J_PMCA__J_PMCA_max * var_J_PMCA__g_PMCA / (1 + pow((var_J_PMCA__K_PMCA / var_chaste_interface__ICC_Membrane__Ca_i), var_J_PMCA__n_PMCA)); // micromolar_per_second
        const double var_J_SERCA__Ke = 0.10000000000000001; // micromolar
        const double var_J_SERCA__Ve = 160; // micromolar_per_second
        const double var_J_SERCA__J_SERCA = pow(var_chaste_interface__ICC_Membrane__Ca_i, 2) * var_J_SERCA__Ve / (pow(var_chaste_interface__ICC_Membrane__Ca_i, 2) + pow(var_J_SERCA__Ke, 2)); // micromolar_per_second
        const double var_J_SERCA__fc = 0.01; // dimensionless
        const double var_J_SERCA__fe = 1; // dimensionless
        const double var_P_SOC__SOC_h = 200; // micromolar
        const double var_P_SOC__SOC_n = 8; // dimensionless
        const double var_P_SOC__P_SOC = 1 / (1 + pow((var_chaste_interface__Ca_er__Ca_er / var_P_SOC__SOC_h), var_P_SOC__SOC_n)); // dimensionless
        const double var_Parameters__Ca_o = 2000; // micromolar
        const double var_Parameters__F = 96.4846; // F_units_ICC
        const double var_Parameters__R = 8.3143999999999991; // R_units_ICC
        const double var_Parameters__T = 310; // Temperature_units
        const double var_Parameters__p2m = 1.0000000000000001e-9; // dimensionless
        const double var_Parameters__z_ca = 2; // dimensionless
        const double var_Nernst__E_Ca = var_Parameters__R * var_Parameters__T * log(var_Parameters__Ca_o / var_chaste_interface__ICC_Membrane__Ca_i) / (var_Parameters__F * var_Parameters__z_ca); // voltage_units
        const double var_I_SOC__I_SOC = (-var_Nernst__E_Ca + var_chaste_interface__ICC_Membrane__Vm) * var_I_SOC__g_SOC * var_P_SOC__P_SOC; // current_units
        const double var_I_LVA_SM__E_Ca = 0.5 * var_Environment__RToF * log(var_Environment__Ca_o / var_chaste_interface__SM_Membrane__Ca_i); // voltage_units
        const double var_I_Ltype_SM__E_Ca = 0.5 * var_Environment__RToF * log(var_Environment__Ca_o / var_chaste_interface__SM_Membrane__Ca_i); // voltage_units
        const double var_I_NSCC_SM__f_ca_NSCC_SM = 1 / (1 + 1.6000000000000004e-15 / pow(var_chaste_interface__SM_Membrane__Ca_i, 4)); // dimensionless
        const double var_J_CaSR_SM__J_CaSR_SM = pow(var_chaste_interface__SM_Membrane__Ca_i, 1.3400000000000001) * var_J_CaSR_SM__J_max_CaSR; // millimolar_per_millisecond
        const double var_SM_Membrane__Cm_SM = 77; // capacitance_units
        const double var_SM_Membrane__K_i = 164; // millimolar
        const double var_I_BK_SM__E_K = var_Environment__RToF * log(var_Environment__K_o / var_SM_Membrane__K_i); // voltage_units
        const double var_I_SK_SM__E_K = var_Environment__RToF * log(var_Environment__K_o / var_SM_Membrane__K_i); // voltage_units
        const double var_I_bk_SM__E_K = var_Environment__RToF * log(var_Environment__K_o / var_SM_Membrane__K_i); // voltage_units
        const double var_I_ka_SM__E_K = var_Environment__RToF * log(var_Environment__K_o / var_SM_Membrane__K_i); // voltage_units
        const double var_I_kr_SM__E_K = var_Environment__RToF * log(var_Environment__K_o / var_SM_Membrane__K_i); // voltage_units
        const double var_SM_Membrane__Na_i = 10; // millimolar
        const double var_I_Na_SM__E_Na = var_Environment__RToF * log(var_Environment__Na_o / var_SM_Membrane__Na_i); // voltage_units
        const double var_I_bk_SM__I_bk_SM = (-var_I_bk_SM__E_K + var_chaste_interface__SM_Membrane__Vm_SM) * var_I_bk_SM__G_max_bk; // current_units
        const double var_I_couple__I_couple = (-var_chaste_interface__SM_Membrane__Vm_SM + var_chaste_interface__ICC_Membrane__Vm) * var_I_couple__g_couple; // current_units
        const double var_SM_Membrane__Vol_SM = 3500; // volume_units
        const double var_Volume__cellPropCyto = 0.69999999999999996; // dimensionless
        const double var_Volume__cellPropER = 0.10000000000000001; // dimensionless
        const double var_Volume__cellVol = 9.9999999999999998e-13; // liter
        const double var_Volume__volCyto = var_Volume__cellPropCyto * var_Volume__cellVol; // liter
        const double var_I_SOC__J_SOC = -var_I_SOC__I_SOC * var_I_SOC__SOCPropCa * var_Parameters__p2m / (var_Parameters__F * var_Parameters__z_ca * var_Volume__volCyto); // micromolar_per_second
        const double var_Volume__volER = var_Volume__cellPropER * var_Volume__cellVol; // liter
        const double var_d_Ano1__Ano1_Vh = -100; // voltage_units
        const double var_d_Ano1__Ano1_n = 2; // dimensionless
        const double var_d_Ano1__Ano1_s = 0.015599999999999999; // voltage_units
        const double var_d_Ano1__Bm = 50; // micromolar
        const double var_d_Ano1__Dc = 250; // micrometer2_per_time
        const double var_d_Ano1__Dm = 75; // micrometer2_per_time
        const double var_d_Ano1__Km = 1; // micromolar
        const double var_d_Ano1__colocalRadius = 0.050000000000000003; // micrometer
        const double var_d_Ano1__d_Ano1_tscale = 1; // dimensionless
        const double var_d_Ano1__kc = 0.01248; // Inverse_Voltage_ICC
        const double var_d_Ano1__nSOC = 50; // dimensionless
        const double var_d_Ano1__mouthCa = 1000000000000000.0 * var_I_SOC__J_SOC * var_Volume__volCyto / var_d_Ano1__nSOC; // micromolar_per_second
        const double var_d_Ano1__rad = var_d_Ano1__colocalRadius; // micrometer
        const double var_d_Ano1__localCa = 0.5 * (2 * sqrt(0.25 * pow((var_chaste_interface__ICC_Membrane__Ca_i * var_d_Ano1__Dc + var_d_Ano1__Dc * var_d_Ano1__Km + 0.5 * var_d_Ano1__mouthCa / (M_PI * var_d_Ano1__rad) - var_d_Ano1__Bm * var_d_Ano1__Dm * var_d_Ano1__Km / (var_chaste_interface__ICC_Membrane__Ca_i + var_d_Ano1__Km)), 2) + var_d_Ano1__Bm * var_d_Ano1__Dc * var_d_Ano1__Dm * var_d_Ano1__Km) + var_chaste_interface__ICC_Membrane__Ca_i * var_d_Ano1__Dc - var_d_Ano1__Dc * var_d_Ano1__Km + 0.5 * var_d_Ano1__mouthCa / (M_PI * var_d_Ano1__rad) - var_d_Ano1__Bm * var_d_Ano1__Dm * var_d_Ano1__Km / (var_chaste_interface__ICC_Membrane__Ca_i + var_d_Ano1__Km)) / var_d_Ano1__Dc; // micromolar
        const double var_d_Ano1__d_Ano1_inf = 1 / ((1 + pow((0.71942446043165476 * var_d_Ano1__localCa / exp(-var_chaste_interface__ICC_Membrane__Vm * var_d_Ano1__kc)), (-var_d_Ano1__Ano1_n))) * (1 + exp((-var_chaste_interface__ICC_Membrane__Vm + var_d_Ano1__Ano1_Vh) * var_d_Ano1__Ano1_s))); // dimensionless
        const double var_d_Ano1__d_Ano1_tau = 0.001 * (81.629999999999995 * exp(-0.56999999999999995 * var_d_Ano1__localCa) + 76.170000000000002 * exp(-0.053740000000000003 * var_d_Ano1__localCa) * exp(0.01422475106685633 * var_chaste_interface__ICC_Membrane__Vm / exp(0.153 * var_d_Ano1__localCa))) * var_d_Ano1__d_Ano1_tscale; // time_units_ICC
        const double d_dt_chaste_interface_var_d_Ano1__d_Ano1 = (-var_chaste_interface__d_Ano1__d_Ano1 + var_d_Ano1__d_Ano1_inf) / var_d_Ano1__d_Ano1_tau; // 1 / time_units
        const double var_d_BK_SM__d_BK_SM = 1 / (1 + exp(-13.815510557964274 - 2 * log(var_chaste_interface__SM_Membrane__Ca_i) - 0.058823529411764705 * var_chaste_interface__SM_Membrane__Vm_SM)); // dimensionless
        const double var_I_BK_SM__I_BK_SM = (-var_I_BK_SM__E_K + var_chaste_interface__SM_Membrane__Vm_SM) * (var_Environment__T_correction_BK + var_I_BK_SM__G_max_BK) * var_d_BK_SM__d_BK_SM; // current_units
        const double var_d_CaT__d_CaT_S = -3; // voltage_units
        const double var_d_CaT__d_CaT_Vh = -40; // voltage_units
        const double var_d_CaT__d_CaT_inf = 1 / (1 + exp((-var_d_CaT__d_CaT_Vh + var_chaste_interface__ICC_Membrane__Vm) / var_d_CaT__d_CaT_S)); // dimensionless
        const double var_d_CaT__d_CaT_tau = 0.0060000000000000001; // time_units_ICC
        const double d_dt_chaste_interface_var_d_CaT__d_CaT = (-var_chaste_interface__d_CaT__d_CaT + var_d_CaT__d_CaT_inf) / var_d_CaT__d_CaT_tau; // 1 / time_units
        const double var_I_CaV__I_CaV = (-var_Nernst__E_Ca + var_chaste_interface__ICC_Membrane__Vm) * var_I_CaV__g_CaV * var_chaste_interface__d_CaV__d_CaV; // current_units
        const double var_I_CaV__J_CaV = -var_I_CaV__I_CaV * var_Parameters__p2m / (var_Parameters__F * var_Parameters__z_ca * var_Volume__volCyto); // micromolar_per_second
        const double var_d_CaV__d_CaV_S = -6; // voltage_units
        const double var_d_CaV__d_CaV_Vh = -26; // voltage_units
        const double var_d_CaV__d_CaV_inf = 1 / (1 + exp((-var_d_CaV__d_CaV_Vh + var_chaste_interface__ICC_Membrane__Vm) / var_d_CaV__d_CaV_S)); // dimensionless
        const double var_d_CaV__d_CaV_tau = 0.0060000000000000001; // time_units_ICC
        const double d_dt_chaste_interface_var_d_CaV__d_CaV = (-var_chaste_interface__d_CaV__d_CaV + var_d_CaV__d_CaV_inf) / var_d_CaV__d_CaV_tau; // 1 / time_units
        const double var_d_KERG__d_KERG_S = -7.0999999999999996; // voltage_units
        const double var_d_KERG__d_KERG_Vh = -35; // voltage_units
        const double var_d_KERG__d_KERG_inf = 1 / (1 + exp((-var_d_KERG__d_KERG_Vh + var_chaste_interface__ICC_Membrane__Vm) / var_d_KERG__d_KERG_S)); // dimensionless
        const double var_d_KERG__d_KERG_tV = -60; // voltage_units
        const double var_d_KERG__d_KERG_ta = 0.14999999999999999; // rate_constants_units_second
        const double var_d_KERG__d_KERG_tau = 1 / (1 + 1 / (1 + exp((-var_d_KERG__d_KERG_tV + var_chaste_interface__ICC_Membrane__Vm) * var_d_KERG__d_KERG_ta))); // time_units_ICC
        const double d_dt_chaste_interface_var_d_KERG__d_KERG = (-var_chaste_interface__d_KERG__d_KERG + var_d_KERG__d_KERG_inf) / var_d_KERG__d_KERG_tau; // 1 / time_units
        const double var_d_KV__d_KV_S = -4.5999999999999996; // voltage_units
        const double var_d_KV__d_KV_Vh = -20; // voltage_units
        const double var_d_KV__d_KV_inf = 1 / (1 + exp((-var_d_KV__d_KV_Vh + var_chaste_interface__ICC_Membrane__Vm) / var_d_KV__d_KV_S)); // dimensionless
        const double var_d_KV__d_KV_tau = 0.044999999999999998; // time_units_ICC
        const double d_dt_chaste_interface_var_d_KV__d_KV = (-var_chaste_interface__d_KV__d_KV + var_d_KV__d_KV_inf) / var_d_KV__d_KV_tau; // 1 / time_units
        const double var_d_LVA_SM__d_inf_LVA_SM = 1 / (1 + exp(-2.5229357798165135 - 0.091743119266055037 * var_chaste_interface__SM_Membrane__Vm_SM)); // dimensionless
        const double var_d_LVA_SM__tau_d_LVA_SM = 3 * var_Environment__T_correction_Ca; // time_units
        const double d_dt_chaste_interface_var_d_LVA_SM__d_LVA_SM = (-var_chaste_interface__d_LVA_SM__d_LVA_SM + var_d_LVA_SM__d_inf_LVA_SM) / var_d_LVA_SM__tau_d_LVA_SM; // 1 / time_units
        const double var_d_Ltype_SM__d_inf_Ltype_SM = 1 / (1 + exp(-3.9534883720930236 - 0.23255813953488372 * var_chaste_interface__SM_Membrane__Vm_SM)); // dimensionless
        const double var_d_Ltype_SM__tau_d_Ltype_SM = 0.46999999999999997 * var_Environment__T_correction_Ca; // time_units
        const double d_dt_chaste_interface_var_d_Ltype_SM__d_Ltype_SM = (-var_chaste_interface__d_Ltype_SM__d_Ltype_SM + var_d_Ltype_SM__d_inf_Ltype_SM) / var_d_Ltype_SM__tau_d_Ltype_SM; // 1 / time_units
        const double var_d_NSV__d_NSV_S = -5; // voltage_units
        const double var_d_NSV__d_NSV_Vh = -30; // voltage_units
        const double var_d_NSV__d_NSV_inf = 1 / (1 + exp((-var_d_NSV__d_NSV_Vh + var_chaste_interface__ICC_Membrane__Vm) / var_d_NSV__d_NSV_S)); // dimensionless
        const double var_d_NSV__d_NSV_tau = 0.0050000000000000001; // time_units_ICC
        const double d_dt_chaste_interface_var_d_NSV__d_NSV = (-var_chaste_interface__d_NSV__d_NSV + var_d_NSV__d_NSV_inf) / var_d_NSV__d_NSV_tau; // 1 / time_units
        const double var_d_NaV__d_NaV_S = -5.5999999999999996; // voltage_units
        const double var_d_NaV__d_NaV_Vh = -25; // voltage_units
        const double var_d_NaV__d_NaV_inf = 1 / (1 + exp((-var_d_NaV__d_NaV_Vh + var_chaste_interface__ICC_Membrane__Vm) / var_d_NaV__d_NaV_S)); // dimensionless
        const double var_d_NaV__d_NaV_t1 = 50; // rate_constants_units_second
        const double var_d_NaV__d_NaV_t2 = 1050; // rate_constants_units_second
        const double var_d_NaV__d_NaV_t3 = -0.059999999999999998; // Inverse_Voltage_ICC
        const double var_d_NaV__d_NaV_t4 = -20; // voltage_units
        const double var_d_NaV__d_NaV_tau = 1 / ((-var_d_NaV__d_NaV_t1 + var_d_NaV__d_NaV_t2) / (1 + exp((-var_d_NaV__d_NaV_t4 + var_chaste_interface__ICC_Membrane__Vm) * var_d_NaV__d_NaV_t3)) + var_d_NaV__d_NaV_t1); // time_units_ICC
        const double d_dt_chaste_interface_var_d_NaV__d_NaV = (-var_chaste_interface__d_NaV__d_NaV + var_d_NaV__d_NaV_inf) / var_d_NaV__d_NaV_tau; // 1 / time_units
        const double var_I_CaT__I_CaT = (-var_Nernst__E_Ca + var_chaste_interface__ICC_Membrane__Vm) * var_I_CaT__g_CaT * var_chaste_interface__d_CaT__d_CaT * var_chaste_interface__f_CaT__f_CaT; // current_units
        const double var_I_CaT__J_CaT = -var_I_CaT__I_CaT * var_Parameters__p2m / (var_Parameters__F * var_Parameters__z_ca * var_Volume__volCyto); // micromolar_per_second
        const double var_f_CaT__f_CaT_S = 5; // voltage_units
        const double var_f_CaT__f_CaT_Vh = -55; // voltage_units
        const double var_f_CaT__f_CaT_inf = 1 / (1 + exp((-var_f_CaT__f_CaT_Vh + var_chaste_interface__ICC_Membrane__Vm) / var_f_CaT__f_CaT_S)); // dimensionless
        const double var_f_CaT__f_CaT_tau = 0.10000000000000001; // time_units_ICC
        const double d_dt_chaste_interface_var_f_CaT__f_CaT = (-var_chaste_interface__f_CaT__f_CaT + var_f_CaT__f_CaT_inf) / var_f_CaT__f_CaT_tau; // 1 / time_units
        const double var_f_KERG__f_KERG_S = 4; // voltage_units
        const double var_f_KERG__f_KERG_Vh = -42; // voltage_units
        const double var_f_KERG__f_KERG_a = 1; // dimensionless
        const double var_f_KERG__f_KERG_inf = 1 - var_f_KERG__f_KERG_a + var_f_KERG__f_KERG_a / (1 + exp((-var_f_KERG__f_KERG_Vh + var_chaste_interface__ICC_Membrane__Vm) / var_f_KERG__f_KERG_S)); // dimensionless
        const double var_f_KERG__f_KERG_tau = 0.0030000000000000001; // time_units_ICC
        const double d_dt_chaste_interface_var_f_KERG__f_KERG = (-var_chaste_interface__f_KERG__f_KERG + var_f_KERG__f_KERG_inf) / var_f_KERG__f_KERG_tau; // 1 / time_units
        const double var_f_KV__f_KV_S = 4.4000000000000004; // voltage_units
        const double var_f_KV__f_KV_Vh = -45; // voltage_units
        const double var_f_KV__f_KV_a = 1; // dimensionless
        const double var_f_KV__f_KV_inf = 1 - var_f_KV__f_KV_a + var_f_KV__f_KV_a / (1 + exp((-var_f_KV__f_KV_Vh + var_chaste_interface__ICC_Membrane__Vm) / var_f_KV__f_KV_S)); // dimensionless
        const double var_f_KV__f_KV_tau = 0.044999999999999998; // time_units_ICC
        const double d_dt_chaste_interface_var_f_KV__f_KV = (-var_chaste_interface__f_KV__f_KV + var_f_KV__f_KV_inf) / var_f_KV__f_KV_tau; // 1 / time_units
        const double var_I_LVA_SM__I_LVA_SM = (-var_I_LVA_SM__E_Ca + var_chaste_interface__SM_Membrane__Vm_SM) * var_I_LVA_SM__G_max_LVA * var_chaste_interface__d_LVA_SM__d_LVA_SM * var_chaste_interface__f_LVA_SM__f_LVA_SM; // current_units
        const double var_f_LVA_SM__f_inf_LVA_SM = 1 / (1 + exp(2.2571428571428571 + 0.14285714285714285 * var_chaste_interface__SM_Membrane__Vm_SM)); // dimensionless
        const double var_f_LVA_SM__tau_f_LVA_SM = 7.5800000000000001 * var_Environment__T_correction_Ca * exp(0.0081700000000000002 * var_chaste_interface__SM_Membrane__Vm_SM); // time_units
        const double d_dt_chaste_interface_var_f_LVA_SM__f_LVA_SM = (-var_chaste_interface__f_LVA_SM__f_LVA_SM + var_f_LVA_SM__f_inf_LVA_SM) / var_f_LVA_SM__tau_f_LVA_SM; // 1 / time_units
        const double var_f_Ltype_SM__f_inf_Ltype_SM = 1 / (1 + exp(4.8314606741573032 + 0.11235955056179775 * var_chaste_interface__SM_Membrane__Vm_SM)); // dimensionless
        const double var_f_Ltype_SM__tau_f_Ltype_SM = 86 * var_Environment__T_correction_Ca; // time_units
        const double d_dt_chaste_interface_var_f_Ltype_SM__f_Ltype_SM = (-var_chaste_interface__f_Ltype_SM__f_Ltype_SM + var_f_Ltype_SM__f_inf_Ltype_SM) / var_f_Ltype_SM__tau_f_Ltype_SM; // 1 / time_units
        const double var_f_NSV__f_NSV_S = 5; // voltage_units
        const double var_f_NSV__f_NSV_Vh = -50; // voltage_units
        const double var_f_NSV__f_NSV_inf = 0.69999999999999996 + 0.29999999999999999 / (1 + exp((-var_f_NSV__f_NSV_Vh + var_chaste_interface__ICC_Membrane__Vm) / var_f_NSV__f_NSV_S)); // dimensionless
        const double var_f_NSV__f_NSV_tau = 0.80000000000000004; // time_units_ICC
        const double d_dt_chaste_interface_var_f_NSV__f_NSV = (-var_chaste_interface__f_NSV__f_NSV + var_f_NSV__f_NSV_inf) / var_f_NSV__f_NSV_tau; // 1 / time_units
        const double var_f_NaV__f_NaV_S = -5.5999999999999996; // voltage_units
        const double var_f_NaV__f_NaV_Vh = -39; // voltage_units
        const double var_f_NaV__f_NaV_inf = 0.46999999999999997 + 0.53000000000000003 / (1 + exp((-var_f_NaV__f_NaV_Vh + var_chaste_interface__ICC_Membrane__Vm) / var_f_NaV__f_NaV_S)); // dimensionless
        const double var_f_NaV__f_NaV_tau = 1; // time_units_ICC
        const double d_dt_chaste_interface_var_f_NaV__f_NaV = (-var_chaste_interface__f_NaV__f_NaV + var_f_NaV__f_NaV_inf) / var_f_NaV__f_NaV_tau; // 1 / time_units
        const double var_I_Ltype_SM__I_Ltype_SM = (-var_I_Ltype_SM__E_Ca + var_chaste_interface__SM_Membrane__Vm_SM) * var_I_Ltype_SM__G_max_Ltype * var_chaste_interface__d_Ltype_SM__d_Ltype_SM * var_chaste_interface__f_Ltype_SM__f_Ltype_SM * var_chaste_interface__f_ca_Ltype_SM__f_ca_Ltype_SM; // current_units
        const double d_dt_chaste_interface_var_SM_Membrane__Ca_i = -var_J_CaSR_SM__J_CaSR_SM + 500 * (-var_I_LVA_SM__I_LVA_SM - var_I_Ltype_SM__I_Ltype_SM) / (var_Environment__F * var_SM_Membrane__Vol_SM); // millimolar / time_units
        const double var_f_ca_Ltype_SM__f_ca_inf_Ltype_SM = 1 - 1 / (1 + exp(23.20534351145038 - 76335.877862595415 * var_chaste_interface__SM_Membrane__Ca_i)); // dimensionless
        const double var_f_ca_Ltype_SM__tau_f_ca_Ltype_SM = 2 * var_Environment__T_correction_Ca; // time_units
        const double d_dt_chaste_interface_var_f_ca_Ltype_SM__f_ca_Ltype_SM = (-var_chaste_interface__f_ca_Ltype_SM__f_ca_Ltype_SM + var_f_ca_Ltype_SM__f_ca_inf_Ltype_SM) / var_f_ca_Ltype_SM__tau_f_ca_Ltype_SM; // 1 / time_units
        const double var_h_Na_SM__h_inf_Na = 1 / (1 + exp(26 + 0.33333333333333331 * var_chaste_interface__SM_Membrane__Vm_SM)); // dimensionless
        const double var_h_Na_SM__tau_h_Na = (5.5 - 0.25 * var_chaste_interface__SM_Membrane__Vm_SM) * var_Environment__T_correction_Na; // time_units
        const double d_dt_chaste_interface_var_h_Na_SM__h_Na_SM = (-var_chaste_interface__h_Na_SM__h_Na_SM + var_h_Na_SM__h_inf_Na) / var_h_Na_SM__tau_h_Na; // 1 / time_units
        const double var_I_NSCC_SM__I_NSCC_SM = (-var_I_NSCC_SM__E_NSCC + var_chaste_interface__SM_Membrane__Vm_SM) * var_I_NSCC_SM__G_max_NSCC_SM * var_I_NSCC_SM__f_ca_NSCC_SM * var_I_NSCC_SM__rach_NSCC_SM * var_chaste_interface__m_NSCC_SM__m_NSCC_SM; // current_units
        const double var_m_NSCC_SM__m_inf_NSCC_SM = 1 / (1 + exp(-1.25 - 0.050000000000000003 * var_chaste_interface__SM_Membrane__Vm_SM)); // dimensionless
        const double var_m_NSCC_SM__tau_m_NSCC_SM = 150 / (1 + exp(-2.5384615384615383 - 0.038461538461538464 * var_chaste_interface__SM_Membrane__Vm_SM)); // time_units
        const double d_dt_chaste_interface_var_m_NSCC_SM__m_NSCC_SM = (-var_chaste_interface__m_NSCC_SM__m_NSCC_SM + var_m_NSCC_SM__m_inf_NSCC_SM) / var_m_NSCC_SM__tau_m_NSCC_SM; // 1 / time_units
        const double var_I_Na_SM__I_Na_SM = (-var_I_Na_SM__E_Na + var_chaste_interface__SM_Membrane__Vm_SM) * var_I_Na_SM__G_max_Na_SM * var_chaste_interface__h_Na_SM__h_Na_SM * var_chaste_interface__m_Na_SM__m_Na_SM; // current_units
        const double var_m_Na_SM__m_inf_Na = 1 / (1 + exp(-9.7916666666666679 - 0.20833333333333334 * var_chaste_interface__SM_Membrane__Vm_SM)); // dimensionless
        const double var_m_Na_SM__tau_m_Na = (0.44 - 0.017000000000000001 * var_chaste_interface__SM_Membrane__Vm_SM) * var_Environment__T_correction_Na; // time_units
        const double d_dt_chaste_interface_var_m_Na_SM__m_Na_SM = (-var_chaste_interface__m_Na_SM__m_Na_SM + var_m_Na_SM__m_inf_Na) / var_m_Na_SM__tau_m_Na; // 1 / time_units
        const double var_neural_input__IP3_effect = 1; // dimensionless
        const double var_neural_input__SK_effect = 1; // dimensionless
        const double var_neural_input__S_e = var_neural_input__IP3_effect * mParameters[2]; // dimensionless
        const double var_J_IPR__IP3 = (1 + var_neural_input__S_e) * var_J_IPR__IP3_base; // micromolar
        const double var_neural_input__S_i = mParameters[3]; // dimensionless
        const double var_neural_input__S_i_SK = var_neural_input__SK_effect * var_neural_input__S_i; // dimensionless
        const double var_x_SK_SM__EC50 = 0.29999999999999999; // micromolar
        const double var_x_SK_SM__n = 2; // dimensionless
        const double var_x_SK_SM__tau_x_SK_SM = 1 / (0.013157894736842105 + 0.047 * var_chaste_interface__SM_Membrane__Ca_i); // time_units
        const double var_I_SK_SM__I_SK_SM = (-var_I_SK_SM__E_K + var_chaste_interface__SM_Membrane__Vm_SM) * var_I_SK_SM__G_max_SK * var_neural_input__S_i_SK * var_chaste_interface__x_SK_SM__x_SK_SM; // current_units
        const double var_x_SK_SM__x_SK_inf_SM = 0.81000000000000005 * pow(var_chaste_interface__SM_Membrane__Ca_i, var_x_SK_SM__n) / (pow(var_chaste_interface__SM_Membrane__Ca_i, var_x_SK_SM__n) + pow(var_x_SK_SM__EC50, var_x_SK_SM__n)); // dimensionless
        const double d_dt_chaste_interface_var_x_SK_SM__x_SK_SM = (-var_chaste_interface__x_SK_SM__x_SK_SM + var_x_SK_SM__x_SK_inf_SM) / var_x_SK_SM__tau_x_SK_SM; // 1 / time_units
        const double var_xa1_SM__tau_xa1_SM = (31.800000000000001 + 175 * exp(-1.9821029982505176 * pow((1 + 0.022522522522522525 * var_chaste_interface__SM_Membrane__Vm_SM), 2))) * var_Environment__T_correction_K; // time_units
        const double var_xa1_SM__xa1_inf_SM = 1 / (1 + exp(-3.3544303797468351 - 0.12658227848101264 * var_chaste_interface__SM_Membrane__Vm_SM)); // dimensionless
        const double d_dt_chaste_interface_var_xa1_SM__xa1_SM = (-var_chaste_interface__xa1_SM__xa1_SM + var_xa1_SM__xa1_inf_SM) / var_xa1_SM__tau_xa1_SM; // 1 / time_units
        const double var_xa2_SM__tau_xa2_SM = 90 * var_Environment__T_correction_K; // time_units
        const double var_I_ka_SM__I_ka_SM = (-var_I_ka_SM__E_K + var_chaste_interface__SM_Membrane__Vm_SM) * var_I_ka_SM__G_max_ka_SM * var_chaste_interface__xa1_SM__xa1_SM * var_chaste_interface__xa2_SM__xa2_SM; // current_units
        const double var_xa2_SM__xa2_inf_SM = 0.10000000000000001 + 0.90000000000000002 / (1 + exp(10.483870967741936 + 0.16129032258064516 * var_chaste_interface__SM_Membrane__Vm_SM)); // dimensionless
        const double d_dt_chaste_interface_var_xa2_SM__xa2_SM = (-var_chaste_interface__xa2_SM__xa2_SM + var_xa2_SM__xa2_inf_SM) / var_xa2_SM__tau_xa2_SM; // 1 / time_units
        const double var_xr1_SM__tau_xr1_SM = 80 * var_Environment__T_correction_K; // time_units
        const double var_xr1_SM__xr1_inf_SM = 1 / (1 + exp(-5.4000000000000004 - 0.20000000000000001 * var_chaste_interface__SM_Membrane__Vm_SM)); // dimensionless
        const double d_dt_chaste_interface_var_xr1_SM__xr1_SM = (-var_chaste_interface__xr1_SM__xr1_SM + var_xr1_SM__xr1_inf_SM) / var_xr1_SM__tau_xr1_SM; // 1 / time_units
        const double var_xr2_SM__tau_xr2_SM = (-707 + 1481 * exp(0.37894736842105264 + 0.010526315789473684 * var_chaste_interface__SM_Membrane__Vm_SM)) * var_Environment__T_correction_K; // time_units
        const double var_I_kr_SM__I_kr_SM = (-var_I_kr_SM__E_K + var_chaste_interface__SM_Membrane__Vm_SM) * var_I_kr_SM__G_max_kr_SM * var_chaste_interface__xr1_SM__xr1_SM * var_chaste_interface__xr2_SM__xr2_SM; // current_units
        const double d_dt_chaste_interface_var_SM_Membrane__Vm_SM = -(-var_I_couple__I_couple + var_I_BK_SM__I_BK_SM + var_I_LVA_SM__I_LVA_SM + var_I_Ltype_SM__I_Ltype_SM + var_I_NSCC_SM__I_NSCC_SM + var_I_Na_SM__I_Na_SM + var_I_SK_SM__I_SK_SM + var_I_bk_SM__I_bk_SM + var_I_ka_SM__I_ka_SM + var_I_kr_SM__I_kr_SM) / var_SM_Membrane__Cm_SM; // voltage_units / time_units
        const double var_xr2_SM__xr2_inf_SM = 0.20000000000000001 + 0.80000000000000004 / (1 + exp(5.7999999999999998 + 0.10000000000000001 * var_chaste_interface__SM_Membrane__Vm_SM)); // dimensionless
        const double d_dt_chaste_interface_var_xr2_SM__xr2_SM = (-var_chaste_interface__xr2_SM__xr2_SM + var_xr2_SM__xr2_inf_SM) / var_xr2_SM__tau_xr2_SM; // 1 / time_units
        const double var_y_bind__k1 = 500; // per_micromolarsecond
        const double var_y_bind__k2 = 0.25; // per_micromolarsecond
        const double var_y_bind__k3 = 500; // per_micromolarsecond
        const double var_y_bind__k4 = 0.25; // per_micromolarsecond
        const double var_y_bind__k5 = 25; // per_micromolarsecond
        const double var_y_bind__k_1 = 65; // rate_constants_units_second
        const double var_y_bind__K1 = var_y_bind__k_1 / var_y_bind__k1; // micromolar
        const double var_y_bind__k_2 = 0.26250000000000001; // rate_constants_units_second
        const double var_y_bind__K2 = var_y_bind__k_2 / var_y_bind__k2; // micromolar
        const double var_y_bind__k_3 = 471.5; // rate_constants_units_second
        const double var_y_bind__K3 = var_y_bind__k_3 / var_y_bind__k3; // micromolar
        const double var_y_bind__k_4 = 0.036249999999999998; // rate_constants_units_second
        const double var_y_bind__K4 = var_y_bind__k_4 / var_y_bind__k4; // micromolar
        const double var_y_bind__k_5 = 2.0499999999999998; // rate_constants_units_second
        const double var_y_bind__K5 = var_y_bind__k_5 / var_y_bind__k5; // micromolar
        const double var_y_bind__phi1 = (var_J_IPR__IP3 * var_y_bind__K4 * var_y_bind__k_2 + var_y_bind__K1 * var_y_bind__K2 * var_y_bind__k_4) * var_chaste_interface__ICC_Membrane__Ca_i / ((var_J_IPR__IP3 + var_y_bind__K1) * var_y_bind__K2 * var_y_bind__K4); // rate_constants_units_second
        const double var_y_bind__phi2 = (var_J_IPR__IP3 * var_y_bind__k_2 + var_y_bind__K3 * var_y_bind__k_4) / (var_J_IPR__IP3 + var_y_bind__K3); // rate_constants_units_second
        const double d_dt_chaste_interface_var_y_bind__y = (1 - var_chaste_interface__y_bind__y) * var_y_bind__phi1 - var_y_bind__phi2 * var_chaste_interface__y_bind__y; // 1 / time_units
        const double var_J_IPR__Pipr = pow((1 - var_chaste_interface__y_bind__y), 3) * pow(var_chaste_interface__ICC_Membrane__Ca_i, 3) * pow(var_J_IPR__IP3, 3) / (pow((var_chaste_interface__ICC_Membrane__Ca_i + var_y_bind__K5), 3) * pow((var_J_IPR__IP3 + var_y_bind__K1), 3)); // dimensionless
        const double var_J_IPR__J_IPR = (-var_chaste_interface__ICC_Membrane__Ca_i + var_chaste_interface__Ca_er__Ca_er) * (var_J_IPR__Pipr * var_J_IPR__kipr + var_J_IPR__Jer); // micromolar_per_second
        const double d_dt_chaste_interface_var_Ca_er__Ca_er = (-var_J_IPR__J_IPR + var_J_SERCA__J_SERCA) * var_J_SERCA__fe * var_Volume__volCyto / var_Volume__volER; // micromolar / time_units
        const double d_dt_chaste_interface_var_ICC_Membrane__Ca_i = (-var_I_NCX__J_NCX - var_J_PMCA__J_PMCA - var_J_SERCA__J_SERCA + var_I_CaT__J_CaT + var_I_CaV__J_CaV + var_I_SOC__J_SOC + var_J_IPR__J_IPR) * var_J_SERCA__fc; // micromolar / time_units

        if (mSetVoltageDerivativeToZero)
        {
            d_dt_chaste_interface_var_ICC_Membrane__Vm = 0.0;
        }
        else
        {
            const double var_ICC_Membrane__Cm_converted = 0.001 * mParameters[0]; // uF
            const double var_I_Ano1__g_Ano1 = 20; // conductance_units
            const double var_I_BK__g_BK = 9; // conductance_units
            const double var_I_BNa__g_BNa = 2; // conductance_units
            const double var_I_KERG__g_KERG = 0; // conductance_units
            const double var_I_KV__g_KV = 0; // conductance_units
            const double var_I_NSCC__g_NSCC = 30; // rate_constants_units_second
            const double var_I_NSV__g_NSV = 0; // conductance_units
            const double var_I_NaV__a_HCl_NaV = 1; // dimensionless
            const double var_I_NaV__a_LCl_NaV = 0; // dimensionless
            const double var_I_NaV__g_NaV = 0; // conductance_units
            const double var_Nernst__E_NSCC = 0; // voltage_units
            const double var_Nernst__E_NSV = 0; // voltage_units
            const double var_P_NSCC__Ca_NSCC = 1.8; // micromolar
            const double var_P_NSCC__n_NSCC = 4; // dimensionless
            const double var_P_NSCC__P_NSCC = pow(var_chaste_interface__ICC_Membrane__Ca_i, var_P_NSCC__n_NSCC) / (pow(var_chaste_interface__ICC_Membrane__Ca_i, var_P_NSCC__n_NSCC) + pow(var_P_NSCC__Ca_NSCC, var_P_NSCC__n_NSCC)); // dimensionless
            const double var_Parameters__Cl_i = 78000; // micromolar
            const double var_Parameters__Cl_o = 166000; // micromolar
            const double var_Parameters__K_i = 140000; // micromolar
            const double var_Parameters__Na_i = 30000; // micromolar
            const double var_Parameters__Na_o = 140000; // micromolar
            const double var_Parameters__z_cl = -1; // dimensionless
            const double var_Nernst__E_Cl = var_Parameters__R * var_Parameters__T * log(var_Parameters__Cl_o / var_Parameters__Cl_i) / (var_Parameters__F * var_Parameters__z_cl); // voltage_units
            const double var_Parameters__z_k = 1; // dimensionless
            const double var_Nernst__E_K = var_Parameters__R * var_Parameters__T * log(mParameters[1] / var_Parameters__K_i) / (var_Parameters__F * var_Parameters__z_k); // voltage_units
            const double var_I_BK__I_BK = (-var_Nernst__E_K + var_chaste_interface__ICC_Membrane__Vm) * var_I_BK__g_BK; // current_units
            const double var_Parameters__z_na = 1; // dimensionless
            const double var_Nernst__E_Na = var_Parameters__R * var_Parameters__T * log(var_Parameters__Na_o / var_Parameters__Na_i) / (var_Parameters__F * var_Parameters__z_na); // voltage_units
            const double var_I_BNa__I_BNa = (-var_Nernst__E_Na + var_chaste_interface__ICC_Membrane__Vm) * var_I_BNa__g_BNa; // current_units
            const double var_ICC_Membrane__I_dummy_converted = GetIntracellularAreaStimulus(var_chaste_interface__Time__time); // uA_per_cm2
            const double var_ICC_Membrane__I_dummy = 999999.99999999988 * var_ICC_Membrane__Cm_converted * var_ICC_Membrane__I_dummy_converted / HeartConfig::Instance()->GetCapacitance(); // current_units
            const double var_I_NCX__I_NCX = -var_I_NCX__J_NCX * var_I_NCX__switch_NCX * var_I_SOC__SOCPropCa * var_Parameters__F * var_Parameters__z_ca * var_Volume__volCyto / var_Parameters__p2m; // current_units
            const double var_I_KERG__I_KERG = (-var_Nernst__E_K + var_chaste_interface__ICC_Membrane__Vm) * var_I_KERG__g_KERG * var_chaste_interface__d_KERG__d_KERG * var_chaste_interface__f_KERG__f_KERG; // current_units
            const double var_I_KV__I_KV = (-var_Nernst__E_K + var_chaste_interface__ICC_Membrane__Vm) * var_I_KV__g_KV * var_chaste_interface__d_KV__d_KV * var_chaste_interface__f_KV__f_KV; // current_units
            const double var_I_NSV__I_NSV = (-var_Nernst__E_NSV + var_chaste_interface__ICC_Membrane__Vm) * var_I_NSV__g_NSV * var_chaste_interface__d_NSV__d_NSV * var_chaste_interface__f_NSV__f_NSV; // current_units
            const double var_I_NaV__f_NaV_new = var_I_NaV__a_LCl_NaV * var_chaste_interface__f_NaV__f_NaV + var_I_NaV__a_HCl_NaV; // dimensionless
            const double var_I_NaV__I_NaV = (-var_Nernst__E_Na + var_chaste_interface__ICC_Membrane__Vm) * var_I_NaV__f_NaV_new * var_I_NaV__g_NaV * var_chaste_interface__d_NaV__d_NaV; // current_units
            const double var_neural_input__Ano1_effect = 0.5; // dimensionless
            const double var_neural_input__NSCC_effect = 0.5; // dimensionless
            const double var_neural_input__S_i_Ano1 = var_neural_input__Ano1_effect * var_neural_input__S_i; // dimensionless
            const double var_d_Ano1__inh_Ano1 = var_chaste_interface__d_Ano1__d_Ano1 * var_neural_input__S_i_Ano1 / (1 + pow((-var_chaste_interface__d_Ano1__d_Ano1 + var_d_Ano1__d_Ano1_inf), 2) / pow(var_d_Ano1__d_Ano1_tau, 2)); // dimensionless
            const double var_I_Ano1__I_Ano1 = (-var_Nernst__E_Cl + var_chaste_interface__ICC_Membrane__Vm) * (-var_d_Ano1__inh_Ano1 + var_chaste_interface__d_Ano1__d_Ano1) * var_I_Ano1__g_Ano1; // current_units
            const double var_neural_input__S_i_NSCC = var_neural_input__NSCC_effect * var_neural_input__S_i; // dimensionless
            const double var_I_NSCC__inh_scale_NSCC = 1 - var_neural_input__S_i_NSCC; // dimensionless
            const double var_I_NSCC__I_NSCC = (-var_Nernst__E_NSCC + var_chaste_interface__ICC_Membrane__Vm) * var_I_NSCC__g_NSCC * var_I_NSCC__inh_scale_NSCC * var_P_NSCC__P_NSCC; // current_units
            const double var_ICC_Membrane__Iion = var_ICC_Membrane__I_dummy + var_I_Ano1__I_Ano1 + var_I_BK__I_BK + var_I_BNa__I_BNa + var_I_CaT__I_CaT + var_I_CaV__I_CaV + var_I_KERG__I_KERG + var_I_KV__I_KV + var_I_NCX__I_NCX + var_I_NSCC__I_NSCC + var_I_NSV__I_NSV + var_I_NaV__I_NaV + var_I_SOC__I_SOC; // current_units
            d_dt_chaste_interface_var_ICC_Membrane__Vm = -var_ICC_Membrane__Iion / mParameters[0]; // voltage_units / time_units
        }
        
        rDY[0] = d_dt_chaste_interface_var_ICC_Membrane__Vm;
        rDY[1] = d_dt_chaste_interface_var_SM_Membrane__Ca_i;
        rDY[2] = d_dt_chaste_interface_var_SM_Membrane__Vm_SM;
        rDY[3] = d_dt_chaste_interface_var_d_Ltype_SM__d_Ltype_SM;
        rDY[4] = d_dt_chaste_interface_var_f_Ltype_SM__f_Ltype_SM;
        rDY[5] = d_dt_chaste_interface_var_f_ca_Ltype_SM__f_ca_Ltype_SM;
        rDY[6] = d_dt_chaste_interface_var_d_LVA_SM__d_LVA_SM;
        rDY[7] = d_dt_chaste_interface_var_f_LVA_SM__f_LVA_SM;
        rDY[8] = d_dt_chaste_interface_var_x_SK_SM__x_SK_SM;
        rDY[9] = d_dt_chaste_interface_var_xr1_SM__xr1_SM;
        rDY[10] = d_dt_chaste_interface_var_xr2_SM__xr2_SM;
        rDY[11] = d_dt_chaste_interface_var_m_Na_SM__m_Na_SM;
        rDY[12] = d_dt_chaste_interface_var_h_Na_SM__h_Na_SM;
        rDY[13] = d_dt_chaste_interface_var_xa1_SM__xa1_SM;
        rDY[14] = d_dt_chaste_interface_var_xa2_SM__xa2_SM;
        rDY[15] = d_dt_chaste_interface_var_m_NSCC_SM__m_NSCC_SM;
        rDY[16] = d_dt_chaste_interface_var_d_CaT__d_CaT;
        rDY[17] = d_dt_chaste_interface_var_f_CaT__f_CaT;
        rDY[18] = d_dt_chaste_interface_var_d_CaV__d_CaV;
        rDY[19] = d_dt_chaste_interface_var_d_NaV__d_NaV;
        rDY[20] = d_dt_chaste_interface_var_f_NaV__f_NaV;
        rDY[21] = d_dt_chaste_interface_var_d_KV__d_KV;
        rDY[22] = d_dt_chaste_interface_var_f_KV__f_KV;
        rDY[23] = d_dt_chaste_interface_var_d_NSV__d_NSV;
        rDY[24] = d_dt_chaste_interface_var_f_NSV__f_NSV;
        rDY[25] = d_dt_chaste_interface_var_d_KERG__d_KERG;
        rDY[26] = d_dt_chaste_interface_var_f_KERG__f_KERG;
        rDY[27] = d_dt_chaste_interface_var_d_Ano1__d_Ano1;
        rDY[28] = d_dt_chaste_interface_var_Ca_er__Ca_er;
        rDY[29] = d_dt_chaste_interface_var_y_bind__y;
        rDY[30] = d_dt_chaste_interface_var_ICC_Membrane__Ca_i;
    }

    std::vector<double> CellICC_SMC_BPFromCellML::ComputeDerivedQuantities(double var_chaste_interface__Time__time, const std::vector<double> & rY)
    {
        // Inputs:
        // Time units: millisecond
        double var_chaste_interface__SM_Membrane__Ca_i = rY[1];
        // Units: millimolar; Initial value: 8e-05
        
        // Mathematics
        const double var_ICC_Membrane__Cm_converted = 0.001 * mParameters[0]; // uF
        const double var_ICC_Membrane__I_dummy_converted = GetIntracellularAreaStimulus(var_chaste_interface__Time__time); // uA_per_cm2

        std::vector<double> dqs(4);
        dqs[0] = var_chaste_interface__Time__time;
        dqs[1] = var_chaste_interface__SM_Membrane__Ca_i;
        dqs[2] = var_ICC_Membrane__Cm_converted;
        dqs[3] = var_ICC_Membrane__I_dummy_converted;
        return dqs;
    }

template<>
void OdeSystemInformation<CellICC_SMC_BPFromCellML>::Initialise(void)
{
    this->mSystemName = "ICC";
    this->mFreeVariableName = "Time__time";
    this->mFreeVariableUnits = "time_units";

    // rY[0]:
    this->mVariableNames.push_back("membrane_voltage");
    this->mVariableUnits.push_back("voltage_units");
    this->mInitialConditions.push_back(-66.0);

    // rY[1]:
    this->mVariableNames.push_back("cytosolic_calcium_concentration");
    this->mVariableUnits.push_back("millimolar");
    this->mInitialConditions.push_back(8e-05);

    // rY[2]:
    this->mVariableNames.push_back("SM_Membrane__Vm_SM");
    this->mVariableUnits.push_back("voltage_units");
    this->mInitialConditions.push_back(-69.75);

    // rY[3]:
    this->mVariableNames.push_back("d_Ltype_SM__d_Ltype_SM");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.0);

    // rY[4]:
    this->mVariableNames.push_back("f_Ltype_SM__f_Ltype_SM");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.95);

    // rY[5]:
    this->mVariableNames.push_back("f_ca_Ltype_SM__f_ca_Ltype_SM");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(1.0);

    // rY[6]:
    this->mVariableNames.push_back("d_LVA_SM__d_LVA_SM");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.02);

    // rY[7]:
    this->mVariableNames.push_back("f_LVA_SM__f_LVA_SM");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.99);

    // rY[8]:
    this->mVariableNames.push_back("x_SK_SM__x_SK_SM");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.0);

    // rY[9]:
    this->mVariableNames.push_back("xr1_SM__xr1_SM");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.0);

    // rY[10]:
    this->mVariableNames.push_back("xr2_SM__xr2_SM");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.82);

    // rY[11]:
    this->mVariableNames.push_back("m_Na_SM__m_Na_SM");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.005);

    // rY[12]:
    this->mVariableNames.push_back("h_Na_SM__h_Na_SM");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.05787);

    // rY[13]:
    this->mVariableNames.push_back("xa1_SM__xa1_SM");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.00414);

    // rY[14]:
    this->mVariableNames.push_back("xa2_SM__xa2_SM");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.72);

    // rY[15]:
    this->mVariableNames.push_back("m_NSCC_SM__m_NSCC_SM");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.0);

    // rY[16]:
    this->mVariableNames.push_back("d_CaT__d_CaT");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.001271016263081);

    // rY[17]:
    this->mVariableNames.push_back("f_CaT__f_CaT");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.5);

    // rY[18]:
    this->mVariableNames.push_back("d_CaV__d_CaV");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.001271016263081);

    // rY[19]:
    this->mVariableNames.push_back("d_NaV__d_NaV");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.0006607800216060858);

    // rY[20]:
    this->mVariableNames.push_back("f_NaV__f_NaV");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(1.0);

    // rY[21]:
    this->mVariableNames.push_back("d_KV__d_KV");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.01);

    // rY[22]:
    this->mVariableNames.push_back("f_KV__f_KV");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.583726132461315);

    // rY[23]:
    this->mVariableNames.push_back("d_NSV__d_NSV");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.001271016263081);

    // rY[24]:
    this->mVariableNames.push_back("f_NSV__f_NSV");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.5);

    // rY[25]:
    this->mVariableNames.push_back("d_KERG__d_KERG");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.001);

    // rY[26]:
    this->mVariableNames.push_back("f_KERG__f_KERG");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.001);

    // rY[27]:
    this->mVariableNames.push_back("d_Ano1__d_Ano1");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.01);

    // rY[28]:
    this->mVariableNames.push_back("Ca_er__Ca_er");
    this->mVariableUnits.push_back("micromolar");
    this->mInitialConditions.push_back(290.0);

    // rY[29]:
    this->mVariableNames.push_back("y_bind__y");
    this->mVariableUnits.push_back("dimensionless");
    this->mInitialConditions.push_back(0.4);

    // rY[30]:
    this->mVariableNames.push_back("ICC_Membrane__Ca_i");
    this->mVariableUnits.push_back("micromolar");
    this->mInitialConditions.push_back(0.14);

    // mParameters[0]:
    this->mParameterNames.push_back("ICC_Membrane__Cm");
    this->mParameterUnits.push_back("capacitance_units_ICC");

    // mParameters[1]:
    this->mParameterNames.push_back("K_o_ICC");
    this->mParameterUnits.push_back("micromolar");

    // mParameters[2]:
    this->mParameterNames.push_back("excitatory_neural");
    this->mParameterUnits.push_back("Hertz");

    // mParameters[3]:
    this->mParameterNames.push_back("inhibitory_neural");
    this->mParameterUnits.push_back("Hertz");

    // Derived Quantity index [0]:
    this->mDerivedQuantityNames.push_back("Time__time");
    this->mDerivedQuantityUnits.push_back("time_units");

    // Derived Quantity index [1]:
    this->mDerivedQuantityNames.push_back("cytosolic_calcium_concentration");
    this->mDerivedQuantityUnits.push_back("millimolar");

    // Derived Quantity index [2]:
    this->mDerivedQuantityNames.push_back("membrane_capacitance");
    this->mDerivedQuantityUnits.push_back("uF");

    // Derived Quantity index [3]:
    this->mDerivedQuantityNames.push_back("membrane_stimulus_current");
    this->mDerivedQuantityUnits.push_back("uA_per_cm2");

    this->mInitialised = true;
}

// Serialization for Boost >= 1.36
#include "SerializationExportWrapperForCpp.hpp"
CHASTE_CLASS_EXPORT(CellICC_SMC_BPFromCellML)

